### ISSUE TITLE
skExtract_FromFBX报错

### ISSUE THREAD

**Issue by dengyang11** [liujf69/Data-Processing#1]
老哥，我运行了你的skExtract_FromFBX.py文件，报错了，
![image](https://github.com/liujf69/Data-Processing/assets/81610054/6b8f8c54-bd1e-4601-a275-382dcb4917f5)
，这是怎么回事呢？

**Comment by liujf69** [comment]
你是使用了我提供的fbx文件嘛？我这边运行是正常的

**Comment by Harry-KIT** [comment]
hi @liujf69 

嗨，首先，感谢您分享有用的资源。如果您不介意的话，我有一个问题要问您。我从您的仓库中找到了 tsstg-model.pth。据我所知，这个模型权重用于基于骨架的动作检测。您是否尝试过使用自定义数据集（而不是识别）实现基于骨架的动作检测。

https://github.com/liujf69/Data-Processing/blob/master/SimCC_Pose/models/TSSTG/tsstg-model.pth
